### ISSUE TITLE
Does not generate png file from msgenny file

### ISSUE THREAD

**Issue by ypwu1** [mscgenjs/mscgenjs-cli#26]
Please provide an example for msgenney generation

### Expected Behavior

`type-password.png` file is genereated. 

### Current Behavior

`type-password.png` file is not genereated.

### Steps to Reproduce (for bugs)

1. create type-password.msgenny  file  with content 
`wordwrapentities=false` <br>
`user -- mobile : enter password` <br>
`user -- mobile : enter passowrd confirmation`<br>

2. mscgenjs -I msgenny -i type-password.msgenny -o type-password.png -T png
### Your Environment

* Version used:  4.0.0
* Node version: 13.2.0
* Operating System and version: Maca OSX catalina
* Link to your project:

**Comment by sverweij** [comment]
hi @ypwu1 - thanks for reaching out on this.

Do you get an error message?

I've tried to reproduce the problem and it seems the input msgenny is not valid on my machine (with the same versions of mscgenjs-cli and node) I get this:

```
~prg/learn/tests $ bin/mscgen_js -I msgenny -i type-password.msgenny -o type-password.png -T png

  syntax error on line 3, column 1:
  Expected ",", ";", comment, lineend, or whitespace but "u" found.
```

Each statement in msgenny ends with a semi colon, and in the content from your issue description they're missing. So if you change the input to something like this:

```msgenny
wordwrapentities=false ;

user -- mobile : enter password ;

user -- mobile : enter passowrd confirmation;
```

You'll get 

![image](https://user-images.githubusercontent.com/4822597/85255234-280da900-b462-11ea-815e-22c435004fa6.png)


P.S. I did run into some other unexpected behaviour, though, where mscgenjs-cli invariably choked with a `Converting circular structure to JSON` error message. If that's the error message you got - it is fixed in  version 4.0.1 - which I have just published.

**Comment by ypwu1** [comment]
Sorry for late reply, @sverweij  I didn't get any error message.  Thanks for correcting syntax error.

**Comment by ypwu1** [comment]
Close this ticket.
